# Generated by Django 3.2.20 on 2023-09-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SheetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('page', models.CharField(max_length=50)),
                ('sheet1', models.CharField(max_length=50)),
                ('ink', models.CharField(max_length=50)),
                ('plates_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('plates_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('plates_amt', models.IntegerField(blank=True, default=0, null=True)),
                ('printing_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('printing_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('printing_amt', models.IntegerField(blank=True, default=0, null=True)),
                ('paper', models.CharField(max_length=50)),
                ('paper_amt', models.IntegerField(blank=True, default=0, null=True)),
                ('lamination', models.CharField(max_length=50)),
                ('lamination_amt', models.IntegerField(blank=True, default=0, null=True)),
                ('binding', models.CharField(max_length=50)),
                ('binding_amt', models.IntegerField(blank=True, default=0, null=True)),
                ('other_gst', models.CharField(max_length=50)),
                ('gst_amt', models.IntegerField(blank=True, default=0, null=True)),
                ('total_this_bill', models.BigIntegerField(blank=True, default=0, null=True)),
                ('previous_bill', models.BigIntegerField(blank=True, default=0, null=True)),
                ('paid', models.BigIntegerField(blank=True, default=0, null=True)),
                ('closing_bal', models.BigIntegerField(blank=True, default=0, null=True)),
                ('paper_rq_sheet', models.CharField(blank=True, max_length=50, null=True)),
                ('paper_rq_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('paper_rq_size', models.CharField(blank=True, max_length=50, null=True)),
                ('paper_rq_gsm', models.CharField(blank=True, max_length=50, null=True)),
                ('paper_rq_vendor', models.CharField(blank=True, max_length=50, null=True)),
                ('paper_rq_amt', models.IntegerField(blank=True, default=0, null=True)),
                ('paper_rq_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('paper_rq_bank', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'sheet_report',
            },
        ),
    ]
