# Generated by Django 3.2.20 on 2023-09-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheetreport',
            old_name='date',
            new_name='header_date',
        ),
    ]
